import { Router } from 'express';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { listApplications, getApplication, updateApplication, advance, reject, reinstate, setInterviewers, myApplications, getTimeline, addFeedback, bulkAdvance, bulkReject, exportCsv } from '../controllers/applications.controller.js';
const router = Router();
router.use(requireAuth);
router.get('/export.csv', requireRole('recruiter'), exportCsv);
router.post('/bulk/advance', requireRole('recruiter'), bulkAdvance);
router.post('/bulk/reject', requireRole('recruiter'), bulkReject);
router.get('/', listApplications);
router.get('/mine', requireRole('interviewer'), myApplications);
router.get('/:id', getApplication);
router.patch('/:id', requireRole('recruiter'), updateApplication);
router.patch('/:id/advance', requireRole('recruiter'), advance);
router.patch('/:id/reject', requireRole('recruiter'), reject);
router.patch('/:id/reinstate', requireRole('recruiter'), reinstate);
router.patch('/:id/interviewers', requireRole('recruiter'), setInterviewers);
router.get('/:id/timeline', getTimeline);
router.post('/:id/feedback', requireRole('interviewer'), addFeedback);
export default router;
